### PR TITLE
Release v0.0.6

### PR DESCRIPTION
**Pull request by webern**
**Issue number:**

N/A

**Description of changes:**

Prepare to release v0.0.6

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Comment by webern** [comment]
> https://github.com/bottlerocket-os/twoliter/compare/f5b46fee7fd04d51db5f775d0c9dc660ce5b3d8a..66239669298491c4be15bfa846ca9b03b0b456db

Oops, check-in the Cargo.lock change

**Comment by webern** [comment]
> https://github.com/bottlerocket-os/twoliter/compare/66239669298491c4be15bfa846ca9b03b0b456db..9cf4563b84c6ec2e42f50c6876c5712208d5c4b2

Rebase

**Comment by webern** [comment]
I've added a commit that will be in a separate PR, then will rebase it out. But I need to test all of this together.

**Comment by webern** [comment]
> https://github.com/bottlerocket-os/twoliter/compare/b9547be628e0ed57f4bbd4f33aff526b5219cd02..03dea54cfc7d70e44ab071d1464ec80bc62b542d

Rebase

**Comment by webern** [comment]
> https://github.com/bottlerocket-os/twoliter/compare/03dea54cfc7d70e44ab071d1464ec80bc62b542d..3f3eb5c37b1584d24ae90ff5dcf59e56476614ed

Rebase

**Comment by webern** [comment]
> https://github.com/bottlerocket-os/twoliter/compare/3f3eb5c37b1584d24ae90ff5dcf59e56476614ed..7307b4d2808dbda69fe90d6a99f9711152043f76

Add the last thing to the Changelog

**Review by gthao313 — APPROVED** [review]

**Review by ecpullen — APPROVED** [review]

**Comment by webern** [comment]
> https://github.com/bottlerocket-os/twoliter/compare/7307b4d2808dbda69fe90d6a99f9711152043f76..b08159bb09fca2ffeef0f76e6a47595ee7b80c0b

Last rebase

**Pull request merged**
