### PR TITLE
makefile.toml

### PR DESCRIPTION
**Pull request by webern**
*Issue #, if available:*

Related to #14

*Description of changes:*

Bring in the history of `Makefile.toml`

Procedure:

```sh
cd /tmp
DIR=/tmp/makefile
rm -rf $DIR
BR=$DIR/bottlerocket
TL=$DIR/twoliter
git clone git@github.com:bottlerocket-os/bottlerocket.git $BR
git clone git@github.com:bottlerocket-os/twoliter.git $TL

cd $BR
git checkout -b monorepo-makefile
git fast-export monorepo-makefile -- Makefile.toml > $DIR/export.fi

cd $TL
git switch --orphan monorepo-makefile
git fast-import < $DIR/export.fi
git checkout develop
git checkout -b makefile-untethered
git merge --signoff --allow-unrelated-histories -m'merge Makefile.toml history' monorepo-makefile
mkdir -p twoliter/embedded
mv Makefile.toml twoliter/embedded
git add --all
git commit -m'move Makefile.toml to twoliter/embedded'

git checkout develop
git checkout -b makefile
git merge --signoff --allow-unrelated-histories makefile-untethered
git push -fu origin makefile
```

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by cbgbt** [comment]
Do you mind describing your process here? Since the commits themselves aren't relevant.

**Comment by webern** [comment]
> Do you mind describing your process here? Since the commits themselves aren't relevant.

Oh yeah, I meant to do that. Updated.

**Review by cbgbt — APPROVED** [review]

**Review by markusboehme — COMMENTED** [review]
History-preserving process looks fine and contents match the current `develop` branch in the mono repo. The `embeded` directory has a typo in its name; would be good to get this fixed before merging lest it becomes too entrenched to change. :-)

As for further development, is the expectation to keep making changes to `Makefile.toml` in both repositories for now?

**Comment by webern** [comment]
> As for further development, is the expectation to keep making changes to `Makefile.toml` in both repositories for now?

For a short period of time, between the merging of this and https://github.com/bottlerocket-os/bottlerocket/pull/3342, changes would need to be made in both places, or a patch would need to be applied here to match bottlerocket develop.

After that, *The Makefile* will exist only here, and the one left behind in Bottlerocket will be a thin facade that will diverge over time.

**Comment by webern** [comment]
> The `embeded` directory has a typo in its name;

Thank you for catching this! Fixed https://github.com/bottlerocket-os/twoliter/compare/5e54155dde8defe169839d70e99ee9b4dda326a0..29844f2cb8f13733fe1873206df301f5ce4ae8fb

**Review by markusboehme — APPROVED** [review]

**Review by bcressey — APPROVED** [review]

**Comment by webern** [comment]
> https://github.com/bottlerocket-os/twoliter/compare/29844f2cb8f13733fe1873206df301f5ce4ae8fb..c97f8fce68bb589523574683ef9e7489958e59a9

Unnecessary force push to see if anything else has landed in Bottlerocket (it hasn't).

**Pull request merged**
